class Autogenerated {
  int? errorCode;
  String? responseString;
  List<Data>? data;
  Null? data1;
  Null? data2;
  Null? data3;

  Autogenerated(
      {this.errorCode,
        this.responseString,
        this.data,
        this.data1,
        this.data2,
        this.data3});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    errorCode = json['error_code'];
    responseString = json['response_string'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
    data1 = json['data1'];
    data2 = json['data2'];
    data3 = json['data3'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error_code'] = this.errorCode;
    data['response_string'] = this.responseString;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['data1'] = this.data1;
    data['data2'] = this.data2;
    data['data3'] = this.data3;
    return data;
  }
}

class Data {
  String? id;
  String? image;
  String? headingPunjabi;
  Null? headingHindi;
  Null? headingEnglish;
  String? descriptionPunjabi;
  Null? descriptionEnglish;
  Null? descriptionHindi;
  String? createdAt;
  String? updatedAt;
  Null? deletedAt;

  Data(
      {this.id,
        this.image,
        this.headingPunjabi,
        this.headingHindi,
        this.headingEnglish,
        this.descriptionPunjabi,
        this.descriptionEnglish,
        this.descriptionHindi,
        this.createdAt,
        this.updatedAt,
        this.deletedAt});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    image = json['image'];
    headingPunjabi = json['heading_punjabi'];
    headingHindi = json['heading_hindi'];
    headingEnglish = json['heading_english'];
    descriptionPunjabi = json['description_punjabi'];
    descriptionEnglish = json['description_english'];
    descriptionHindi = json['description_hindi'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    deletedAt = json['deleted_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['image'] = this.image;
    data['heading_punjabi'] = this.headingPunjabi;
    data['heading_hindi'] = this.headingHindi;
    data['heading_english'] = this.headingEnglish;
    data['description_punjabi'] = this.descriptionPunjabi;
    data['description_english'] = this.descriptionEnglish;
    data['description_hindi'] = this.descriptionHindi;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['deleted_at'] = this.deletedAt;
    return data;
  }
}

